# Generated by Django 4.1.2 on 2022-10-25 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=68)),
                ('email', models.CharField(max_length=68)),
                ('pass_hash', models.CharField(max_length=1024)),
                ('bio', models.CharField(default='This is a demo bio, bio cannot be edited right now it will be edited afterwords if necessary.', max_length=1024)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
