# Generated by Django 4.1.2 on 2022-10-25 04:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=68)),
                ('client_name', models.CharField(max_length=68)),
                ('sale_amount', models.FloatField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
