# Generated by Django 4.1.2 on 2022-10-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_sales_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to="upload_to ='uploads/% Y/% m/% d/% H/% M/% s/")),
            ],
        ),
    ]
