# Generated by Django 4.1.2 on 2022-10-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
